### ISSUE TITLE
每次编译产生的Debug文件夹，也要加到gitignore里面，并且不要上传上来啦。

### ISSUE THREAD

**Issue by imchangchang** [imchangchang/ToyCode_CharlesHuang#6]
讲道理，git commit里面的文件不应该有二进制文件

debug文件夹都是编译过程中的中间文件，这种东西不需要上传的，因为对其他人没有任何用处。

**Comment by hcbdreamer** [comment]
我上传的文件没有debug文件夹啊，之前我自己写了一个ignore文件，是直接把两个debug文件夹都ignore了的，后来看GitHub上有官方的就拿来用了，发现也是把debug文件夹内部的东西都ignore了
